document.body.style.backgroundColor = 'orange';
var iframe = document.createElement('iframe'); 
iframe.style.background = "green";
iframe.style.height = "100%";
iframe.style.width = "360px";
iframe.style.position = "fixed";
iframe.style.top = "0px";
iframe.style.right = "0px";
iframe.style.zIndex = "9000000000000000000";
iframe.style.border= "none"; 
iframe.src=browser.extension.getURL("/popup/note.html");
document.body.appendChild(iframe);